version: "3.6"
networks:
  pyspark_network:
services:
  pyspark:
    image: jupyter/pyspark-notebook
    hostname: pyspark
    networks:
      - pyspark_network
    command: "start.sh jupyter lab --NotebookApp.token='' --NotebookApp.password=''"
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
    volumes:
      - ./notebooks/Pregel.ipynb:/home/jovyan/work/Pregel.ipynb
      - ./doc/5.graph:/home/jovyan/work/imgs
