version: "3.6"
networks:
  pyspark_network:
services:
  pyspark:
    build:
      context: .
    hostname: pyspark
    networks:
      - pyspark_network
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
    volumes:
      - ./notebooks/Streaming.ipynb:/home/jovyan/work/Streaming.ipynb
      - ./notebooks/spark-catboost.ipynb:/home/jovyan/work/spark-catboost.ipynb
  redpanda:
    image: docker.redpanda.com/vectorized/console
    restart: on-failure
    hostname: redpanda
    networks:
      - pyspark_network
    ports:
      - "18080:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    hostname: zookeeper
    networks:
      - pyspark_network
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.3.1'
    hostname: kafka
    networks:
      - pyspark_network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLIENT_USERS=docker
      - KAFKA_CLIENT_PASSWORDS=docker
    depends_on:
      - zookeeper
